---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    my_list:
      - name: name1
        tier1: tier1
      - name: my-segment-vip-1
        tier1: tier1
      - name: mysegment
        tier1: mytier1


  tasks:

    - name: Debug
      debug:
        msg: "{{ nsxt.network_management.name }}"


    - name: Debug
      debug:
        msg: "{{ item.0.name }}"
      loop: "{{ nsxt.networks_data  | from_json | product(my_list) | list }}"
      when:
        - item.0.name == item.1.name

