---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Debug
      debug:
        msg: "{{ nsxt.network_management.name }}"



    - set_fact:
        network_mgmt_details: "{{ network_mgmt_details | default({}) | combine ({'address': item.cidr.split('/')[0], 'mask': item.cidr.split('/')[1], 'tier1': item.tier1, 'begin': item.avi_ipam_pool.split('-')[0], 'end': item.avi_ipam_pool.split('-')[1]}) }}"
      loop: "{{ nsxt.segments_overlay }}"
      tags:
        - cloud
        - nsxtApi
      when:
        - item.display_name == nsxt.network_management.name


    - name: Debug
      debug:
        msg: "{{ network_mgmt_details.tier1 }}"
