---
- hosts: localhost

  vars:

    list1:
      - 1
      - 2
      - 3
    list2:
      - 4
      - 5
      - 6
    list3:
      - 7
      - 8
      - 9
      - 10
    list4:
      - 7
      - 8
      - 9
      - 10
    list5:
      - 7
      - 8
      - 9

  tasks:

    - name: Debug the three lists in //
      debug:
        msg: "{{ item.0, item.1, item.2 }}"
      loop: "{{ list1 | zip(list2, list3) | list }}"

    - name: productize list1 over list4
      debug:
        msg: "attempt {{ my_idx  + 1 }}: {{ item.0, item.1 }}"
      loop: "{{ list1 | product(list4) }}"
      loop_control:
        index_var: my_idx

    - name: productize list1 over (list2 and list5)
      debug:
        msg: "attempt {{ my_idx  + 1 }}: {{ item.0, item.1.0, item.1.1 }}"
      loop: "{{ list1 | product(list2 | zip(list5) | list) }}"
      loop_control:
        index_var: my_idx
