---
- hosts: localhost

  vars:

    list1:
      - 1
      - 2
      - 3
    list2:
      - 4
      - 5
      - 6
    list3:
      - 7
      - 8
      - 9

  tasks:

    - name: Debug
      debug:
        msg: "{{ item.0, item.1, item.2 }}"
      loop: "{{ list1 | zip(list2, list3) | list }}"


    - name: Debug
      debug:
        msg: "{{ my_idx  + 1 }}:{{ item.0.0, item.0.1, item.1 }}"
      loop: "{{ list1 | zip(list2) | product(list3) | list }}"
      loop_control:
        index_var: my_idx


    - name: Debug
      debug:
        msg: "{{ my_idx  + 1 }}:{{ item.0, item.1}}"
      loop: "{{ list1 | zip(list2) | list }}"
      loop_control:
        index_var: my_idx
