---
- hosts: localhost
  gather_facts: no
  
  vars:
    list1:
      - name: pool1
        servers:
          - 1.1.1.1
          - 2.2.2.2
      - name: pool2
        servers:
          - 1.1.1.1
          - 2.2.2.2



  tasks:

    - name: Debug variable with subelements
      debug:
        msg: "{{ item.0 }} - {{ item.1 }} - {{ my_idx + 1 }}"
      with_subelements:
        - "{{ list1 }}"
        - servers
      loop_control:
        label: "Update {{ item.0.name }}"
        index_var: my_idx

    - name: Debug variable with subelements
      debug:
        msg: "{{ item.0.name }} - {{ item.1 }} - {{ my_idx + 1 }}"
      loop: "{{ list1 | subelements('servers') }}"
      loop_control:
        label: "Update {{ item.0.name }}"
        index_var: my_idx
