- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    my_cidr: 10.1.3.0/24
    my_ip: 10.15.4.1/24
    my_ip_index: 1

  tasks:


    - name: My IP variable
      no_log: True
      debug:
        msg: "{{ my_ip }}"


    - name: My IP address
      debug:
        msg: "{{ my_ip | ipv4('address') }}"

    - name: Debug cidr network from ip
      debug:
        msg: "{{ my_ip | ipv4('network') }}"

    - name: Debug cidr prefix from ip
      debug:
        msg: "{{ my_ip | ipaddr('prefix') }}"

    - name: Debug ip pool start from ip
      debug:
        msg: "{{ my_ip | ipaddr(my_ip_index) | ipv4('address') }}"


    - name: Debug
      debug:
        msg: "{{ my_cidr }}"

    - name: Debug
      debug:
        msg: "{{ my_ip_index }}"


    - name: Debug
      debug:
        msg: "{{ my_cidr | ipaddr(my_ip_index) }}"


